#!/usr/bin/env python3
"""
Make-to-Markdown 工业级后置清洗引擎 (v3.6)

对 markitdown 转换产物执行 RAG 质量优化，确保：
  清晰的标题层级 + 纯净的文本内容 + 文档级摘要 + 结构化数据 + 完整的上下文

用法:
    python post_clean.py input.md
    python post_clean.py input.md -o cleaned.md --summary
    python post_clean.py input.md --summary-file summary.txt -o cleaned.md
    python post_clean.py input.md --check-only

输出指标：
  - noise_removed:   噪声清除数
  - heading_fixes:   标题修复数
  - table_fixes:     表格修复数
  - chunk_ready:     是否可直接用于 RAG 切片
"""

import re
import sys
import argparse
import json
from pathlib import Path
from typing import List, Tuple, Dict


# ═══════════════════════════════════════════════════════════════
# 1. 噪声模式库
# ═══════════════════════════════════════════════════════════════

NOISE_PATTERNS: List[Tuple[re.Pattern, str]] = [
    # 工具水印
    (re.compile(r'^\s*\[Generated by[^\]]*\]\s*$', re.MULTILINE), ''),
    (re.compile(r'^\s*\*Converted by markitdown[^*]*\*\s*$', re.MULTILINE), ''),
    (re.compile(r'^\s*\[Created with[^\]]*\]\s*$', re.MULTILINE), ''),
    (re.compile(r'^\s*Powered by[^\n]*markitdown[^\n]*$', re.MULTILINE), ''),
    # 页码
    (re.compile(r'^\s*Page\s+\d+\s+of\s+\d+\s*$', re.MULTILINE | re.IGNORECASE), ''),
    (re.compile(r'^\s*---\s*Page\s+\d+\s*---\s*$', re.MULTILINE | re.IGNORECASE), ''),
    (re.compile(r'^\s*\[PAGE\s*\d+\]\s*$', re.MULTILINE | re.IGNORECASE), ''),
    (re.compile(r'^\s*\d{1,4}\s*$', re.MULTILINE), ''),
    # 文档标记
    (re.compile(r'^\s*Confidential\s*[-–—].*$', re.MULTILINE | re.IGNORECASE), ''),
    (re.compile(r'^\s*DRAFT\s*.*$', re.MULTILINE | re.IGNORECASE), ''),
    (re.compile(r'^\s*Internal Use Only\s*$', re.MULTILINE | re.IGNORECASE), ''),
    (re.compile(r'^\s*For Review Only\s*$', re.MULTILINE | re.IGNORECASE), ''),
    (re.compile(r'^\s*\u00a9\s*\d{4}.*$', re.MULTILINE), ''),
    (re.compile(r'^\s*All Rights Reserved\.?\s*$', re.MULTILINE), ''),
    # 空白
    (re.compile(r'\n{3,}'), '\n\n'),
    (re.compile(r'[ \t]+$', re.MULTILINE), ''),
    (re.compile(r'^\s*\n', re.MULTILINE), '\n'),
]


# ═══════════════════════════════════════════════════════════════
# 2. 标题解析
# ═══════════════════════════════════════════════════════════════

def parse_headings(content: str) -> List[dict]:
    """解析所有标题行，返回 [{line_idx, level, text}]"""
    headings = []
    for idx, line in enumerate(content.split('\n')):
        m = re.match(r'^(#{1,6})\s+(.+)', line)
        if m:
            headings.append({
                'line_idx': idx,
                'level': len(m.group(1)),
                'text': m.group(2).strip(),
            })
    return headings


# ═══════════════════════════════════════════════════════════════
# 3. 标题层级修复
# ═══════════════════════════════════════════════════════════════

def fix_heading_hierarchy(content: str) -> Tuple[str, List[str]]:
    """
    修复标题层级（从后往前处理避免索引错位）：
    1. 多个 H1 → 第一个保留，其余降 H2
    2. 越级标题 → 在前插入过渡标题
    """
    lines = content.split('\n')
    headings = parse_headings(content)
    fixes = []

    if not headings:
        return content, fixes

    # 收集修复动作（index 基于原始 lines）
    actions = []  # [(原始line_idx, 'demote'|'insert', new_text)]

    # 动作1: 多 H1 降级（从第2个H1开始）
    first_h1 = True
    for h in headings:
        if h['level'] == 1:
            if not first_h1:
                actions.append((h['line_idx'], 'demote', h['text']))
                fixes.append(f"H1→H2: 「{h['text']}」")
            first_h1 = False

    # 动作2: 越级检测
    prev_level = 1
    for i, h in enumerate(headings):
        jump = h['level'] - prev_level
        if jump > 1:
            fixes.append(f"标题越级 L{prev_level}→L{h['level']}: 「{h['text']}」")
            # 在越级标题前插入过渡
            actions.append((h['line_idx'], 'insert_before', h['level'] - 1, h['text']))
        prev_level = h['level']

    # 从后往前应用修复（避免索引错位）
    actions.sort(key=lambda a: a[0], reverse=True)

    for act in actions:
        if act[1] == 'demote':
            idx, _, text = act
            lines[idx] = f"## {text}"
        elif act[1] == 'insert_before':
            idx, _, target_level, ref_text = act
            prefix = '#' * target_level
            lines.insert(idx, f"\n{prefix} {ref_text}（概述）\n")

    return '\n'.join(lines), fixes


# ═══════════════════════════════════════════════════════════════
# 4. 表格修复
# ═══════════════════════════════════════════════════════════════

def fix_tables(content: str) -> Tuple[str, List[str]]:
    """为缺失分隔符的表格补全 |---|---|---| 行"""
    lines = content.split('\n')
    fixes = []
    i = 0
    in_table = False  # 标记是否已在某个表格内部（已补过或已有分隔符）
    while i < len(lines) - 1:
        current = lines[i].strip()
        if current.startswith('|') and current.endswith('|'):
            cols = [c.strip() for c in current.split('|')[1:-1]]
            if len(cols) >= 2:
                next_line = lines[i + 1].strip() if i + 1 < len(lines) else ''
                # 下一行是分隔符 → 进入表格，跳过
                if re.match(r'^\|[\s\-:]+\|', next_line):
                    in_table = True
                    i += 2
                    continue
                # 下一行是非表格行 → 可能不是表格，或表格结束
                if not next_line.startswith('|') or next_line.startswith('>'):
                    in_table = False
                    i += 1
                    continue
                # 下一行是数据行：若尚未在当前表格内 → 补分隔符
                if not in_table:
                    sep = '| ' + ' | '.join('---' for _ in cols) + ' |'
                    lines.insert(i + 1, sep)
                    fixes.append(f"补分隔符: 「{current[:40]}...」")
                    in_table = True
                    i += 2  # 跳过刚插入的分隔符
                    continue
        else:
            in_table = False  # 非表格行，退出表格状态
        i += 1
    return '\n'.join(lines), fixes


# ═══════════════════════════════════════════════════════════════
# 5. 上下文面包屑（轻量版，避免大量注入导致超时）
# ═══════════════════════════════════════════════════════════════

def inject_breadcrumbs(content: str, headings: List[dict]) -> Tuple[str, List[str]]:
    """
    仅对 H2 注入父级 H1 上下文字段，跳过嵌套过深的结构。
    每个 H2 注入后额外跳过以避免重复。
    """
    if not headings or len(headings) > 200:  # 超过 200 标题不注入（避免超时）
        return content, []

    lines = content.split('\n')
    injected = []
    h1_title = None
    offset = 0

    for h in headings:
        if h['level'] == 1:
            h1_title = h['text']

    if not h1_title:
        return content, []

    for h in headings:
        if h['level'] != 2:
            continue
        actual_idx = h['line_idx'] + offset
        breadcrumb = f"> 📍 {h1_title} > {h['text']}"
        # 检查下一行是否已有面包屑
        next_idx = actual_idx + 1
        if next_idx < len(lines) and lines[next_idx].startswith('> 📍'):
            continue
        lines.insert(next_idx, breadcrumb)
        offset += 1
        injected.append(breadcrumb)
        if len(injected) >= 100:  # 最多 100 个面包屑
            break

    return '\n'.join(lines), injected


# ═══════════════════════════════════════════════════════════════
# 6. 文档摘要生成
# ═══════════════════════════════════════════════════════════════

def generate_summary(content: str, headings: List[dict]) -> str:
    """基于标题层级和数据自动生成摘要"""
    parts = []
    title = headings[0]['text'] if headings else "未命名文档"
    h2_list = [h['text'] for h in headings if h['level'] == 2]

    parts.append(f"本文档「{title}」")
    if h2_list:
        parts.append(f"，涵盖 {len(h2_list)} 个章节")
    if len(h2_list) <= 8:
        parts.append(f"：{'、'.join(h2_list)}")

    # 数据点
    numbers = re.findall(r'(\d+\.?\d*\s*(?:亿|万|%|倍|个百分点))', content)
    if numbers:
        unique = list(dict.fromkeys(numbers))[:4]
        parts.append(f"。关键数据：{', '.join(unique)}")

    tables = len(re.findall(r'^\| ---', content, re.MULTILINE))
    parts.append(f"。含 {tables} 个数据表格")

    return ''.join(parts) + '。'


# ═══════════════════════════════════════════════════════════════
# 7. 质量评估
# ═══════════════════════════════════════════════════════════════

def assess_quality(content: str, noise_count: int, heading_fix_count: int,
                   table_fix_count: int, breadcrumb_count: int) -> dict:
    """评估 RAG 物料质量"""
    headings = parse_headings(content)
    h1 = sum(1 for h in headings if h['level'] == 1)
    h2 = sum(1 for h in headings if h['level'] == 2)
    h3 = sum(1 for h in headings if h['level'] == 3)
    tables = len(re.findall(r'^\|[\s\-:]+\|', content, re.MULTILINE))

    issues = []
    if h1 == 0:
        issues.append("缺少 H1 顶层标题")
    if h1 > 1:
        issues.append(f"存在 {h1} 个 H1，建议仅保留 1 个")
    if h2 == 0 and h3 > 0:
        issues.append("存在 H3 但无 H2，建议补充中间层级")

    chunk_ready = (h1 == 1 and h2 >= 1 and noise_count == 0
                   and heading_fix_count == 0 and table_fix_count == 0)

    return {
        "noise_removed": noise_count,
        "heading_fixes": heading_fix_count,
        "table_fixes": table_fix_count,
        "breadcrumbs": breadcrumb_count,
        "structure": f"H1:{h1} H2:{h2} H3:{h3}",
        "tables": tables,
        "chunk_ready": chunk_ready,
        "issues": issues,
    }


def format_report(report: dict) -> str:
    lines = [
        "=" * 50,
        "  RAG 物料质量报告",
        "=" * 50,
        f"  噪声行移除:     {report['noise_removed']}",
        f"  标题问题修复:   {report['heading_fixes']}",
        f"  表格修复:       {report['table_fixes']}",
        f"  上下文锚点:     {report['breadcrumbs']}",
        f"  标题结构:       {report['structure']}",
        f"  数据表格:       {report['tables']}",
        f"  RAG 就绪:       {'是' if report['chunk_ready'] else '否'}",
    ]
    if report['issues']:
        lines.append("  注意事项:")
        for issue in report['issues']:
            lines.append(f"    - {issue}")
    return '\n'.join(lines)


# ═══════════════════════════════════════════════════════════════
# 8. 主流程
# ═══════════════════════════════════════════════════════════════

def process(content: str, add_summary: bool = False,
            add_breadcrumbs: bool = True) -> Tuple[str, dict]:
    """一站式处理：清洗 + 修复 + 增强 → RAG 物料"""

    noise_count = 0
    # Step 1: 噪声清除
    for pattern, replacement in NOISE_PATTERNS:
        new_content = pattern.sub(replacement, content)
        if new_content != content:
            noise_count += 1
        content = new_content

    content = re.sub(r'\n{3,}', '\n\n', content)

    # Step 2: 标题修复
    content, heading_fixes = fix_heading_hierarchy(content)

    # Step 3: 表格修复
    content, table_fixes = fix_tables(content)

    # Step 4: 面包屑注入
    breadcrumb_count = 0
    if add_breadcrumbs:
        headings = parse_headings(content)
        content, injected = inject_breadcrumbs(content, headings)
        breadcrumb_count = len(injected)

    # Step 5: 摘要
    if add_summary:
        headings = parse_headings(content)
        summary = generate_summary(content, headings)
        content = f"> **文档摘要**\n> {summary}\n\n---\n\n{content}"

    # Step 6: 质量评估
    report = assess_quality(content, noise_count, len(heading_fixes),
                             len(table_fixes), breadcrumb_count)

    return content.strip() + '\n', report


def main():
    parser = argparse.ArgumentParser(description="Make-to-Markdown 工业级后置清洗引擎")
    parser.add_argument("input", help="输入的 Markdown 文件路径")
    parser.add_argument("--output", "-o", default=None, help="输出文件路径")
    parser.add_argument("--summary", action="store_true", help="注入文档级摘要")
    parser.add_argument("--no-breadcrumbs", action="store_true", help="禁用上下文面包屑")
    parser.add_argument("--quality-report", action="store_true", help="输出质量报告 JSON")
    parser.add_argument("--summary-file", default=None, help="从文件读取自定义摘要文本")
    parser.add_argument("--check-only", action="store_true", help="仅检查结构不修改文件")
    parser.add_argument("--quiet", "-q", action="store_true", help="静默模式")
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"错误：文件不存在 {args.input}", file=sys.stderr)
        sys.exit(1)

    content = input_path.read_text(encoding="utf-8")

    # --check-only：仅分析结构，不修改
    if args.check_only:
        headings = parse_headings(content)
        h1 = sum(1 for h in headings if h['level'] == 1)
        h2 = sum(1 for h in headings if h['level'] == 2)
        h3 = sum(1 for h in headings if h['level'] == 3)
        tables = len(re.findall(r'^\|[\s\-:]+\|', content, re.MULTILINE))

        issues = []
        if h1 == 0:
            issues.append("缺少 H1 顶层标题")
        if h1 > 1:
            issues.append(f"存在 {h1} 个 H1，建议仅保留 1 个")
        if h2 == 0 and h3 > 0:
            issues.append("存在 H3 但无 H2，建议补充中间层级")
        # 越级检测
        prev_level = 1
        for h in headings:
            if h['level'] - prev_level > 1:
                issues.append(f"标题越级 L{prev_level}→L{h['level']}: 「{h['text']}」")
            prev_level = h['level']

        print(f"标题结构: H1={h1} H2={h2} H3={h3}")
        print(f"数据表格: {tables}")
        if issues:
            print("问题:")
            for i in issues:
                print(f"  - {i}")
        else:
            print("结构正常")
        return

    cleaned, report = process(
        content,
        add_summary=args.summary,
        add_breadcrumbs=not args.no_breadcrumbs,
    )

    # --summary-file：从文件读取自定义摘要并注入
    if args.summary_file:
        sf_path = Path(args.summary_file)
        if sf_path.exists():
            custom_summary = sf_path.read_text(encoding="utf-8").strip()
            # 替换或注入摘要块
            if cleaned.startswith("> **文档摘要**"):
                cleaned = re.sub(
                    r'^> \*\*文档摘要\*\*\n> .+?\n\n---\n\n',
                    f'> **文档摘要**\n> {custom_summary}\n\n---\n\n',
                    cleaned, count=1,
                )
            else:
                cleaned = f'> **文档摘要**\n> {custom_summary}\n\n---\n\n{cleaned}'
        else:
            print(f"警告：摘要文件不存在 {args.summary_file}", file=sys.stderr)

    output_path = Path(args.output) if args.output else input_path
    # 写入前先备份：若目标路径已存在，rename→.bak 再写，防止清洗损坏后原始文件不可恢复
    if output_path.exists():
        bak_path = output_path.with_suffix(output_path.suffix + '.bak')
        output_path.rename(bak_path)
        output_path.write_text(cleaned, encoding="utf-8")
        try:
            bak_path.unlink()
        except Exception:
            pass
    else:
        output_path.write_text(cleaned, encoding="utf-8")

    if args.quality_report:
        print(json.dumps(report, ensure_ascii=False, indent=2))

    if not args.quiet:
        print(format_report(report))
        print(f"\n输出: {output_path}")


if __name__ == "__main__":
    main()
